apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: student-test
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: student_management
  MYSQL_USER: student
  MYSQL_PASSWORD: student123
