name: Build and deploy JAR app to Azure Web App - do

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4


      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: maven


      - name: Build Spring Boot application
        run: |
          mvn clean package -DskipTests


      - name: Verify generated jar
        run: |
          ls -lh target/


      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar



  deploy:

    runs-on: ubuntu-latest

    needs: build

    permissions:
      id-token: write
      contents: read


    steps:


      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app


      - name: Verify downloaded jar
        run: |
          ls -lh


      - name: Login Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1D6D9A1259DB4F2FB96A9EA859E0D75E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1D40A7DEE7CC402DA91922A493E682FF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_491997D3E65842C7A3B552FEA7B8BA91 }}


      - name: Deploy JAR to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'do'
          slot-name: Production
          package: '*.jar'
